### ISSUE TITLE
Write Java version of Sieve

### ISSUE THREAD

**Issue by ArcticLight** [hawkw/Sieve#1]
implement the required parts.
- [x] primes
- [x] upper
- [x] lower
- [x] groupname_Sieve()
- [x] processSieve()
- [x] getBoundaries ()
- [x] showPrimes ()

**Comment by hawkw** [comment]
Done as of commit https://github.com/hawkw/Sieve/commit/3164088e7a67a7a53b76496fcbc9021106d4a6b1
